In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("./datasets/연간보고서19.csv", encoding='CP949')

In [2]:
data.shape

(1472, 19)

In [3]:
data1=data

In [4]:
column_list=data.columns[3:]

In [5]:
column_list

Index(['자산(*)(연결)', '자산(*)', '영업이익(손실)', '영업이익(손실)(연결)', '부채(*)(연결)', '부채(*)',
       '자본(*)(연결)', '자본(*)', '매출액(영업수익)(*)(연결)', '매출액(영업수익)(*)', '유동자산(*)(연결)',
       '유동자산(*)', '유동부채(*)(연결)', '유동부채(*)', '이익잉여금(*)(연결)', '이익잉여금(*)'],
      dtype='object')

In [6]:
# if df_1["복리후생비(연결)(천원)"]
from tqdm import tqdm
import numpy as np
for i in tqdm(np.arange(0,len(column_list),2)):
    for j in range(data1.shape[0]):
        if np.isnan(data1[column_list[i]][j]) :
            data1[column_list[i]][j]=data1[column_list[i+1]][j]

  0%|          | 0/8 [00:00<?, ?it/s]C:\Users\dbswo\AppData\Local\Temp\ipykernel_13692\346431395.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1[column_list[i]][j]=data1[column_list[i+1]][j]
100%|██████████| 8/8 [00:00<00:00, 11.40it/s]

In [7]:
data==data1

,회사명,거래소코드,회계년도,자산(*)(연결),자산(*),영업이익(손실),영업이익(손실)(연결),부채(*)(연결),부채(*),자본(*)(연결),자본(*),매출액(영업수익)(*)(연결),매출액(영업수익)(*),유동자산(*)(연결),유동자산(*),유동부채(*)(연결),유동부채(*),이익잉여금(*)(연결),이익잉여금(*)
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1467,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1468,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1469,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True
1470,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1471,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True

In [8]:
len(data1.columns)

19

In [9]:
len(data1.columns[np.arange(4,20,2)])
data1=data1.drop(data1.columns[np.arange(4,20,2)],axis=1)

In [10]:
data1.columns

Index(['회사명', '거래소코드', '회계년도', '자산(*)(연결)', '영업이익(손실)', '부채(*)(연결)',
       '자본(*)(연결)', '매출액(영업수익)(*)(연결)', '유동자산(*)(연결)', '유동부채(*)(연결)',
       '이익잉여금(*)(연결)'],
      dtype='object')

In [11]:
a=['회사명', '거래소코드', '회계년도', '자산', '영업이익', '부채', '자본', '매출액', '유동자산', '유동부채', '이익잉여금']

In [12]:
data1.columns=a

In [13]:
data1

,회사명,거래소코드,회계년도,자산,영업이익,부채,자본,매출액,유동자산,유동부채,이익잉여금
0,(주)CMG제약,58820,2019/12,192243166.0,2603774.0,12084883.0,180158283.0,58622681.0,150584066.0,9306387.0,5054709.0
1,(주)ES큐브,50120,2019/12,463958680.0,587700.0,389920168.0,74038512.0,43708239.0,359030693.0,230135454.0,6015932.0
2,(주)가비아,79940,2019/12,199916131.0,4889113.0,64956993.0,134959139.0,148306878.0,86880807.0,43098923.0,70637536.0
3,(주)강스템바이오텍,217730,2019/12,113643697.0,-19411148.0,44924460.0,68719236.0,6004584.0,55408095.0,20598774.0,-77231627.0
4,(주)강원에너지,114190,2019/12,56602063.0,-17150531.0,35477506.0,21124556.0,42549622.0,30544232.0,30840573.0,-8042133.0
...,...,...,...,...,...,...,...,...,...,...,...
1467,효성오앤비(주),97870,2019/06,70203765.0,1331706.0,6641029.0,63562735.0,28376911.0,36812995.0,5071188.0,50317324.0
1468,휴림로봇(주),90710,2019/12,42734247.0,-3879766.0,14263432.0,28470815.0,17620760.0,26232830.0,13239812.0,-46543830.0
1469,휴마시스(주),205470,2019/12,36487811.0,-875264.0,21243825.0,15243986.0,9150652.0,25771471.0,15471882.0,-9240555.0
1470,휴젤(주),145020,2019/12,894690014.0,41865498.0,150419075.0,744270939.0,204567625.0,640910847.0,37568296.0,768284514.0
1471,흥구석유(주),24060,2019/12,83661499.0,500763.0,6660240.0,77001259.0,150668735.0,22619714.0,4660149.0,40649728.0

In [14]:
data1

,회사명,거래소코드,회계년도,자산,영업이익,부채,자본,매출액,유동자산,유동부채,이익잉여금
0,(주)CMG제약,58820,2019/12,192243166.0,2603774.0,12084883.0,180158283.0,58622681.0,150584066.0,9306387.0,5054709.0
1,(주)ES큐브,50120,2019/12,463958680.0,587700.0,389920168.0,74038512.0,43708239.0,359030693.0,230135454.0,6015932.0
2,(주)가비아,79940,2019/12,199916131.0,4889113.0,64956993.0,134959139.0,148306878.0,86880807.0,43098923.0,70637536.0
3,(주)강스템바이오텍,217730,2019/12,113643697.0,-19411148.0,44924460.0,68719236.0,6004584.0,55408095.0,20598774.0,-77231627.0
4,(주)강원에너지,114190,2019/12,56602063.0,-17150531.0,35477506.0,21124556.0,42549622.0,30544232.0,30840573.0,-8042133.0
...,...,...,...,...,...,...,...,...,...,...,...
1467,효성오앤비(주),97870,2019/06,70203765.0,1331706.0,6641029.0,63562735.0,28376911.0,36812995.0,5071188.0,50317324.0
1468,휴림로봇(주),90710,2019/12,42734247.0,-3879766.0,14263432.0,28470815.0,17620760.0,26232830.0,13239812.0,-46543830.0
1469,휴마시스(주),205470,2019/12,36487811.0,-875264.0,21243825.0,15243986.0,9150652.0,25771471.0,15471882.0,-9240555.0
1470,휴젤(주),145020,2019/12,894690014.0,41865498.0,150419075.0,744270939.0,204567625.0,640910847.0,37568296.0,768284514.0
1471,흥구석유(주),24060,2019/12,83661499.0,500763.0,6660240.0,77001259.0,150668735.0,22619714.0,4660149.0,40649728.0

In [15]:
data1.to_csv('./datasets/연간보고서19.csv',encoding='CP949', index=None)

In [13]:
a = pd.read_csv('최최최종.csv', encoding='CP949')
a

,Unnamed: 0,회사명,거래소코드,회계년도,자산,부채,자본,매출액,매출원가,매출총이익,...,유형자산,이익잉여금,이자비용,영업활동으로 인한 현금흐름,투자활동으로 인한 현금흐름,재무활동으로 인한 현금흐름,이자수익,법인세비용,지분법이익,지분법손실
0,0,(주)CMG제약,58820,2012/06,25729348.0,9349464.0,16379884.0,8315805.0,5796611.0,2519194.0,...,9456783.0,-47627766.0,94250.0,19573.0,-1280742.0,1216470.0,NaN,0.0,NaN,0.0
1,1,(주)CMG제약,58820,2013/06,57504018.0,25581391.0,31922628.0,10459871.0,6205112.0,4254759.0,...,10410888.0,-52118586.0,730993.0,468850.0,-2149157.0,0.0,8562982.0,0.0,0.0,0.0
2,2,(주)CMG제약,58820,2014/06,57514553.0,8073098.0,49441455.0,11041662.0,6735639.0,4306023.0,...,17388609.0,-51834607.0,59583.0,183382.0,1171028.0,0.0,-9210190.0,0.0,0.0,0.0
3,3,(주)CMG제약,58820,2015/06,57102877.0,8417950.0,48684927.0,12564650.0,8193272.0,4371377.0,...,18086092.0,-52807304.0,65162.0,79696.0,-163720.0,0.0,-4930652.0,0.0,0.0,0.0
4,4,(주)CMG제약,58820,2016/06,57554452.0,9261045.0,48293407.0,15835051.0,9725741.0,6109310.0,...,17137844.0,-55655555.0,0.0,36734.0,889218.0,666196.0,-1960522.0,-58901.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8531,8531,흥구석유(주),24060,2019/06,75845846.0,6264393.0,69581453.0,72592664.0,68687188.0,3905476.0,...,34906987.0,33229922.0,1987.0,38202.0,1015568.0,-1854398.0,NaN,234292.0,NaN,0.0
8532,8532,흥구석유(주),24060,2014/06,68823855.0,3814565.0,65009290.0,98684299.0,94549691.0,4134607.0,...,42872957.0,28657759.0,0.0,0.0,2053641.0,-3404225.0,NaN,190298.0,NaN,0.0
8533,8533,흥구석유(주),24060,2013/06,75064308.0,10481076.0,64583232.0,126595587.0,122584478.0,4011110.0,...,44581278.0,28231701.0,0.0,0.0,2290500.0,-2458725.0,NaN,205804.0,NaN,0.0
8534,8534,흥구석유(주),24060,2012/06,72990312.0,9632794.0,63357518.0,138760547.0,134637075.0,4123472.0,...,44922151.0,27005987.0,0.0,0.0,3019365.0,-2727041.0,NaN,204717.0,NaN,0.0
8535,8535,흥구석유(주),24060,2015/06,70719373.0,3406954.0,67312418.0,82051119.0,78540760.0,3510359.0,...,40454822.0,30960887.0,0.0,0.0,2911019.0,-652041.0,NaN,514397.0,NaN,0.0

In [14]:
a['회계년도'].unique()

array(['2012/06', '2013/06', '2014/06', '2015/06', '2016/06', '2017/06',
       '2018/06', '2019/06', '2019', '2016/12', '2018/12', '2017/12',
       '2014/12', '2015/12', '2012/12', '2013/12', '2019/09', '2018/09',
       '2017/09', '2015/09', '2012/09', '2014/09', '2016/09', '2013/09',
       '2012/03', '2019/12', '2013/03', '2014/03', '2015/03', '2019/01',
       '2019/03', '2017/03', '2018/03', '2016/03', '2019/08', '2018/08',
       '2018/02', '2012/02', '2013/02', '2014/02', '2015/02', '2016/02',
       '2017/02', '2019/02', '2012/04'], dtype=object)

In [26]:
data2=pd.read_csv('./최종(태환).csv',encoding='CP949',index_col=0)

In [27]:
data2.shape

(8525, 30)