In [1]:
import pandas as pd
import re

In [2]:
data = pd.read_csv('./news/뉴스_2014.csv')
data

,기업,기사발행일,기사제목,뉴스기사본문
0,디아이디,2014.12.18. 오전 11:08,"<생생코스닥> 디아이디, 무선충전 관련 특허취득",디아이디는 웨어러블 디바이스의 무선 충전을 위한 스마트폰 및 그 무선전력 송신 방법...
1,디아이디,2014.12.04. 오전 9:09,"<특징주> 디아이디, 최대주주 지분매각 불발에 급락",(서울=연합뉴스) 김남권 기자 = 디아이디의 주가가 최대주주의 지분 매각 불발 소식...
2,디아이디,2014.12.03. 오후 8:59,디아이디 매각 무산,디에스아이 인수 자금 조달 실패로\n\n정보기술(IT) 부품업체 디아이디(07413...
3,디아이디,2014.12.04. 오후 5:24,"[마켓포커스]디아이디, 지분매각 불발 '급락'",이 기사는 12월4일 아시아경제TV를 통해 방송된 내용입니다.\n\n앵커> 지난달 ...
4,디아이디,2014.12.04. 오전 11:03,"디아이디, 공진형 무선 충전 관련 특허 취득",[ 권민경 기자 ] 디아이디는 '공진형 무선 충전 수신기의 다중 조절 스위치 장치와...
...,...,...,...,...
1411,리홈쿠첸,2014.10.17. 오후 3:18,"리홈쿠첸, 中 캔톤 페어 참가 ""판매 인프라 강화 기대""",[머니투데이 김건우 기자]\n본문 이미지 영역\n생활가전 전문기업 리홈쿠첸은 중국 ...
1412,리홈쿠첸,2014.10.28. 오전 9:59,"리홈쿠첸, 전기레인지 매출 급성장 중","리홈쿠첸(014470)(01447)은 전기압력밥솥 매출이 49.3%, 전기레인지 및..."
1413,리홈쿠첸,2014.10.17. 오전 11:24,"리홈쿠첸, 캔톤페어 참가","【서울=뉴시스】생활가전 전문기업 리홈쿠첸(대표 이대희, www.lihom-cuche..."
1414,리홈쿠첸,2014.10.17. 오전 11:10,"[포토] (주)리홈쿠첸, 중국 최대 무역전시회 캔톤페어 참가-3",[이데일리 신종오 기자]\n\n생활가전 전문기업 리홈쿠첸이 중국 광저우에서 열리는 ...
1415,리홈쿠첸,2014.10.15. 오후 2:47,"리홈쿠첸, 노원에서 '사랑의 밥상' 진행","[머니투데이 김건우 기자][이대희 대표 참가, 나눔 문화 확산에의 포부 밝혀]\n\..."

In [3]:
data.groupby('기업').count()

         기사발행일  기사제목  뉴스기사본문
기업
CJ프레시웨이     69    69      69
GT&T        15    15      15
KCW         44    44      44
KG이니시스      57    57      57
데브시스터즈      46    46      46
디아이디        79    79      79
리노공업        81    81      81
리드코프        68    68      68
리홈쿠첸        53    53      53
산성앨엔에스      72    72      72
슈피겐코리아      77    77      77
에이스하이텍      90    90      90
영진코퍼레이션     74    74      74
와이즈파워       64    64      64
울트라건설       61    61      61
잘만테크        57    57      57
코나아이        61    61      61
태창파로스       81    81      81
티에스엠텍       76    76      76
포스코ICT      25    25      25
하이록코리아      65    65      65
해피드림       101   101     101

In [83]:
제거할기사제목 = ['증시 일정', '증시일정', '장마감후', '장 마감 후', '장마감공시', '증시 캘린더', '재송', '투자정보', \
    '코스닥 기업공시', '장중 주요', '코스닥 3분기 결산', '주요 뉴스 및 공시', '기업공시',' 기업 공시', '장 종료 후', \
        '특징주A/S', '주요 정보', '오전 공시', '투자정보', '기업 공시', '오늘의 메모', '재테크 캘린더', '추천주 정리', '희망복원 주식클리닉', \
        '\d{1,2}월 \d{1,2}일', '오늘의 주요 공시', '코스닥 공시', '코스닥 메모', '대박 공모주', '<표>']
제거제목리스트 = '|'.join(제거할기사제목)

In [84]:
data_unique = data.drop_duplicates(['뉴스기사본문'])
data_result = data_unique[~data_unique['기사제목'].str.contains(제거제목리스트, na=False, case=False)]
#data_result.to_csv('dd.csv')

In [85]:
data_result.groupby('기업').count()

         기사발행일  기사제목  뉴스기사본문
기업
CJ프레시웨이     69    69      69
GT&T        12    12      12
KCW         22    22      22
KG이니시스      52    52      52
데브시스터즈      46    46      46
디아이디        59    59      59
리노공업        71    71      71
리드코프        47    47      47
리홈쿠첸        53    53      53
산성앨엔에스      64    64      64
슈피겐코리아      76    76      76
에이스하이텍      43    43      43
영진코퍼레이션     50    50      50
와이즈파워       36    36      36
울트라건설       55    55      55
잘만테크        52    52      52
코나아이        61    61      61
태창파로스       57    57      57
티에스엠텍       54    54      54
포스코ICT      25    25      25
하이록코리아      59    59      59
해피드림        48    48      48

In [89]:
pattern1 = r'\([^)]*\)'
#pattern2 = r'\[[^)]*\]'
pattern2 = r"\[([^]]+)\]"

data_result['뉴스기사본문전처리'] = [re.sub(pattern1, '', s) for s in data_result['뉴스기사본문']]
data_result['뉴스기사본문전처리'] = [re.sub(pattern2, '', s) for s in data_result['뉴스기사본문전처리']]
data_result['뉴스기사본문전처리'] = [re.sub('[^/^$|\s+/가-힣\.]', '', s) for s in data_result['뉴스기사본문전처리']]
data_result['뉴스기사본문전처리'] = [re.sub('[[ \s]{2,}\.{2,}]', '', s) for s in data_result['뉴스기사본문전처리']]
data_result['뉴스기사본문전처리'] = [re.sub('\n', '', s) for s in data_result['뉴스기사본문전처리']]
data_result
data_result.to_csv('dd.csv', index=None)

C:\Users\dbswo\AppData\Local\Temp\ipykernel_11312\226564118.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_result['뉴스기사본문전처리'] = [re.sub(pattern1, '', s) for s in data_result['뉴스기사본문']]
C:\Users\dbswo\AppData\Local\Temp\ipykernel_11312\226564118.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_result['뉴스기사본문전처리'] = [re.sub(pattern2, '', s) for s in data_result['뉴스기사본문전처리']]
C:\Users\dbswo\AppData\Local\Temp\ipykernel_11312\226564118.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_result['뉴스기사본문전처리'] = [re.sub('[^/^$|\s+/가-힣\.]', '', s) for s in data_result['뉴스기사본문전처리']]
C:\Users\dbswo\AppData\Local\Temp\ipykernel_11312\226564118.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_result['뉴스기사본문전처리'] = [re.sub('[[ \s]{2,}\.{2,}]', '', s) for s in data_result['뉴스기사본문전처리']]
C:\Users\dbswo\AppData\Local\Temp\ipykernel_11312\226564118.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_result['뉴스기사본문전처리'] = [re.sub('\n', '', s) for s in data_result['뉴스기사본문전처리']]

In [90]:
data_result['뉴스기사본문전처리'].loc[4]

' 디아이디는 공진형 무선 충전 수신기의 다중 조절 스위치 장치와 그 방법에 대한 특허를 취득했다고 일 공시했다.한경닷컴 권민경 기자 .     성공을 부르는 습관 한경닷컴 무단 전재 및 재배포 금지'